"""magic link tokens

Revision ID: eaf251037874
Revises: 426cb94e5675
Create Date: 2026-06-25 22:37:23.634331

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'eaf251037874'
down_revision: Union[str, Sequence[str], None] = '426cb94e5675'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('magiclinktoken',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('token_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('expiration', sa.DateTime(), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('magiclinktoken', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_magiclinktoken_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_magiclinktoken_token_hash'), ['token_hash'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('magiclinktoken', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_magiclinktoken_token_hash'))
        batch_op.drop_index(batch_op.f('ix_magiclinktoken_email'))

    op.drop_table('magiclinktoken')
    # ### end Alembic commands ###
